import { normalizeShow } from '@/lib/normalize';
import { Show } from '@/lib/types';

export const sampleShows: Show[] = [
  normalizeShow({
    id: 'toronto-danforth-2026-04-06',
    date: '2026-04-06',
    city: 'Toronto, ON',
    venue_name: 'The Danforth Hall',
    venue_address: '456 Danforth Ave, Toronto, ON',
    venue_maps_url: 'https://maps.google.com/?q=456+Danforth+Ave+Toronto+ON',
    dos_name: 'Maya Chen',
    dos_phone: '+1 (416) 555-0191',
    parking_load_info: 'Load-in via rear alley off Bowden. Sprinter can park behind the venue until 11 PM. Trailer moves after load-in.',
    schedule_items: [
      { id: '1', label: 'Load-in', time: '3:00 PM' },
      { id: '2', label: 'Soundcheck', time: '4:30 PM' },
      { id: '3', label: 'Doors', time: '7:00 PM' },
      { id: '4', label: 'TourBook', time: '8:00 PM' },
      { id: '5', label: 'Curfew', time: '11:00 PM' },
    ],
    hotel_name: 'Broadview Suites',
    hotel_address: '88 Broadview Ave, Toronto, ON',
    hotel_maps_url: 'https://maps.google.com/?q=88+Broadview+Ave+Toronto+ON',
    hotel_notes: '2 queen rooms under TourBook hold. Parking clearance is 6’8”.',
    notes: 'Merch settle with DOS after curfew.',
    guest_list_notes: '5 guest list spots total.',
    visibility: {
      show_venue: true,
      show_parking_load_info: true,
      show_schedule: true,
      show_dos_contact: true,
      show_accommodation: true,
      show_notes: true,
      show_guest_list_notes: true,
    },
    created_at: '2026-03-15T10:00:00.000Z',
  }),
  normalizeShow({
    id: 'montreal-rialto-2026-04-08',
    date: '2026-04-08',
    city: 'Montreal, QC',
    venue_name: 'Rialto Theatre',
    venue_address: '5723 Park Ave, Montreal, QC',
    venue_maps_url: 'https://maps.google.com/?q=5723+Park+Ave+Montreal+QC',
    dos_name: 'Etienne Roy',
    dos_phone: '+1 (514) 555-0142',
    parking_load_info: 'Bus unload at stage door on Bernard. No overnight parking at venue.',
    schedule_items: [
      { id: '1', label: 'Load-in', time: '2:30 PM' },
      { id: '2', label: 'Soundcheck', time: '4:00 PM' },
      { id: '3', label: 'Doors', time: '7:30 PM' },
      { id: '4', label: 'TourBook', time: '8:30 PM' },
      { id: '5', label: 'Curfew', time: '11:30 PM' },
    ],
    hotel_name: 'Hotel Mile End',
    hotel_address: '155 Avenue du Mont-Royal E, Montreal, QC',
    hotel_maps_url: 'https://maps.google.com/?q=155+Avenue+du+Mont-Royal+E+Montreal+QC',
    hotel_notes: 'Front desk needs vehicle plate numbers at check-in.',
    created_at: '2026-03-16T10:00:00.000Z',
  }),
  normalizeShow({
    id: 'ottawa-bronson-2026-04-10',
    date: '2026-04-10',
    city: 'Ottawa, ON',
    venue_name: 'Bronson Centre',
    venue_address: '211 Bronson Ave, Ottawa, ON',
    venue_maps_url: 'https://maps.google.com/?q=211+Bronson+Ave+Ottawa+ON',
    dos_name: 'Jules Parker',
    dos_phone: '+1 (613) 555-0179',
    parking_load_info: 'Merch can roll through front lobby after 5 PM only.',
    schedule_items: [
      { id: '1', label: 'Load-in', time: '3:30 PM' },
      { id: '2', label: 'Support', time: '7:15 PM' },
      { id: '3', label: 'TourBook', time: '8:15 PM' },
      { id: '4', label: 'Curfew', time: '11:00 PM' },
      { id: '5', label: 'Lobby call', time: 'TBD' },
    ],
    hotel_name: 'Capital Stay Hotel',
    hotel_address: '120 Kent St, Ottawa, ON',
    hotel_maps_url: 'https://maps.google.com/?q=120+Kent+St+Ottawa+ON',
    hotel_notes: '3 rooms on artist rate.',
    created_at: '2026-03-17T10:00:00.000Z',
  }),
  normalizeShow({
    id: 'detroit-st-andrews-2025-11-12',
    date: '2025-11-12',
    city: 'Detroit, MI',
    venue_name: 'St. Andrew’s Hall',
    venue_address: '431 E Congress St, Detroit, MI',
    venue_maps_url: 'https://maps.google.com/?q=431+E+Congress+St+Detroit+MI',
    dos_name: 'Avery Hall',
    dos_phone: '+1 (313) 555-0104',
    parking_load_info: 'Trailer parking in secured lot behind the venue.',
    schedule_items: [
      { id: '1', label: 'Load-in', time: '2:00 PM' },
      { id: '2', label: 'Doors', time: '7:00 PM' },
      { id: '3', label: 'TourBook', time: '9:00 PM' },
      { id: '4', label: 'Curfew', time: '11:00 PM' },
      { id: '5', label: '', time: '' },
    ],
    notes: 'Past sample show for year grouping.',
    visibility: {
      show_venue: true,
      show_parking_load_info: true,
      show_schedule: true,
      show_dos_contact: true,
      show_accommodation: false,
      show_notes: true,
      show_guest_list_notes: false,
    },
    created_at: '2025-10-15T10:00:00.000Z',
  }),
  normalizeShow({
    id: 'chicago-metro-2024-09-04',
    date: '2024-09-04',
    city: 'Chicago, IL',
    venue_name: 'Metro',
    venue_address: '3730 N Clark St, Chicago, IL',
    venue_maps_url: 'https://maps.google.com/?q=3730+N+Clark+St+Chicago+IL',
    dos_name: 'Chris Olsen',
    dos_phone: '+1 (773) 555-0128',
    parking_load_info: 'Load through alley door on the north side.',
    schedule_items: [
      { id: '1', label: 'Load-in', time: '1:30 PM' },
      { id: '2', label: 'Doors', time: '7:00 PM' },
      { id: '3', label: 'TourBook', time: '8:30 PM' },
      { id: '4', label: 'Curfew', time: '11:00 PM' },
      { id: '5', label: '', time: '' },
    ],
    created_at: '2024-08-20T10:00:00.000Z',
  }),
];
