import { Show } from '@/lib/types';

export const sampleShows: Show[] = [
  {
    id: 'toronto-danforth-2026-04-06',
    date: '2026-04-06',
    city: 'Toronto, ON',
    venue_name: 'The Danforth Hall',
    venue_address: '456 Danforth Ave, Toronto, ON',
    venue_maps_url: 'https://maps.google.com/?q=456+Danforth+Ave+Toronto+ON',
    dos_name: 'Maya Chen',
    dos_phone: '+1 (416) 555-0191',
    parking_load_info:
      'Load-in via rear alley off Bowden. Sprinter can park behind the venue until 11 PM. Trailer must move to the Green P lot after load-in.',
    load_in: '3:00 PM',
    soundcheck: '4:30 PM',
    doors: '7:00 PM',
    show_time: '8:00 PM',
    curfew: '11:00 PM',
    hotel_name: 'Broadview Suites',
    hotel_address: '88 Broadview Ave, Toronto, ON',
    hotel_maps_url: 'https://maps.google.com/?q=88+Broadview+Ave+Toronto+ON',
    hotel_notes: '2 queen rooms under TourBook hold. Parking clearance is 6’8”. Breakfast starts at 6:30 AM.',
    created_at: '2026-03-15T10:00:00.000Z',
  },
  {
    id: 'montreal-rialto-2026-04-08',
    date: '2026-04-08',
    city: 'Montreal, QC',
    venue_name: 'Rialto Theatre',
    venue_address: '5723 Park Ave, Montreal, QC',
    venue_maps_url: 'https://maps.google.com/?q=5723+Park+Ave+Montreal+QC',
    dos_name: 'Etienne Roy',
    dos_phone: '+1 (514) 555-0142',
    parking_load_info:
      'Bus unload at stage door on Bernard. No overnight parking at venue. Ask security for cone access before backing in.',
    load_in: '2:30 PM',
    soundcheck: '4:00 PM',
    doors: '7:30 PM',
    show_time: '8:30 PM',
    curfew: '11:30 PM',
    hotel_name: 'Hotel Mile End',
    hotel_address: '155 Avenue du Mont-Royal E, Montreal, QC',
    hotel_maps_url: 'https://maps.google.com/?q=155+Avenue+du+Mont-Royal+E+Montreal+QC',
    hotel_notes: 'Front desk needs vehicle plate numbers at check-in. Late-night food spot two blocks east.',
    created_at: '2026-03-16T10:00:00.000Z',
  },
  {
    id: 'ottawa-bronson-2026-04-10',
    date: '2026-04-10',
    city: 'Ottawa, ON',
    venue_name: 'Bronson Centre',
    venue_address: '211 Bronson Ave, Ottawa, ON',
    venue_maps_url: 'https://maps.google.com/?q=211+Bronson+Ave+Ottawa+ON',
    dos_name: 'Jules Parker',
    dos_phone: '+1 (613) 555-0179',
    parking_load_info:
      'Merch can roll through front lobby after 5 PM only. Trailer parking arranged in staff lot; code will be texted day-of.',
    load_in: '3:30 PM',
    soundcheck: '5:00 PM',
    doors: '7:00 PM',
    show_time: '8:15 PM',
    curfew: '11:00 PM',
    hotel_name: 'Capital Stay Hotel',
    hotel_address: '120 Kent St, Ottawa, ON',
    hotel_maps_url: 'https://maps.google.com/?q=120+Kent+St+Ottawa+ON',
    hotel_notes: '3 rooms on artist rate. Use side entrance for gear if arriving before standard check-in.',
    created_at: '2026-03-17T10:00:00.000Z',
  },
];
